### PR TITLE
Adding validation

### PR DESCRIPTION
**Pull request by mterzo**
I put together the basic metadata as well validated the code.  If found that the code had lots of compilation issues.  I added CI so that these get tested.

Ruby version 1.8.7 does not support array splatting which is causing the 1.8.7 to fail, if this isn't require, should move this from the 1.8.7 test matrix.

### CODE REVIEW

**Comment by LaynePeng** [comment]
Thanks for the PR, especially you add the CI to this repo.

**Comment by mterzo** [comment]
Do we care about 1.8.7 ruby failing?

Also, you should setup a travic-ci for the emccode, so MRs get tested.

**Comment by LaynePeng** [comment]
Thanks for the suggestion, I just added travic-ci. And I care about the fail, rather than see the fail, I'd like to set the requirment to 1.9.3~ I think 1.9.3 has been release for a long time, it is reasonable to make it as least support version.

**Comment by mterzo** [comment]
Or move the few place you use array splatting to generate arrays options to vnz commands. The puppet community still supports puper 4 on ruby 1.8.7.

**Pull request merged**
